---
- name: install fish shell
  package:
    name: fish
    state: present

- name: install tmux
  package:
    name: tmux
    state: present

- name: install neovim
  package:
    name: neovim
    state: present

- name: install curl
  package:
    name: curl
    state: present

- name: install tree
  package:
    name: tree
    state: present

- name: install keepassx
  package:
    name: keepassx
    state: present